blank_issues_enabled: false
contact_links:
  - name: â“ Ask a question or discuss an idea
    url: https://github.com/make-software/casper-dao-middleware/discussions
    about: Ask your questions and discuss your ideas

